import 'package:flutter/material.dart';

Map<String, TextStyle> blackTextStyles = {
  '14N': const TextStyle(fontSize: 14, color: Colors.black, fontWeight: FontWeight.normal),
  '14B': const TextStyle(fontSize: 14, color: Colors.black, fontWeight: FontWeight.bold),
  '16N': const TextStyle(fontSize: 16, color: Colors.black, fontWeight: FontWeight.normal),
  '16B': const TextStyle(fontSize: 16, color: Colors.black, fontWeight: FontWeight.bold),
  '18N': const TextStyle(fontSize: 18, color: Colors.black, fontWeight: FontWeight.normal),
  '18B': const TextStyle(fontSize: 18, color: Colors.black, fontWeight: FontWeight.bold),
  '20N': const TextStyle(fontSize: 20, color: Colors.black, fontWeight: FontWeight.normal),
  '20B': const TextStyle(fontSize: 20, color: Colors.black, fontWeight: FontWeight.bold),
  '22N': const TextStyle(fontSize: 22, color: Colors.black, fontWeight: FontWeight.normal),
  '22B': const TextStyle(fontSize: 22, color: Colors.black, fontWeight: FontWeight.bold),
  '24N': const TextStyle(fontSize: 24, color: Colors.black, fontWeight: FontWeight.normal),
  '24B': const TextStyle(fontSize: 24, color: Colors.black, fontWeight: FontWeight.bold),
  '26N': const TextStyle(fontSize: 26, color: Colors.black, fontWeight: FontWeight.normal),
  '26B': const TextStyle(fontSize: 26, color: Colors.black, fontWeight: FontWeight.bold),
  '28N': const TextStyle(fontSize: 28, color: Colors.black, fontWeight: FontWeight.normal),
  '28B': const TextStyle(fontSize: 28, color: Colors.black, fontWeight: FontWeight.bold),
  '30N': const TextStyle(fontSize: 30, color: Colors.black, fontWeight: FontWeight.normal),
  '30B': const TextStyle(fontSize: 30, color: Colors.black, fontWeight: FontWeight.bold),
  '32N': const TextStyle(fontSize: 32, color: Colors.black, fontWeight: FontWeight.normal),
  '32B': const TextStyle(fontSize: 32, color: Colors.black, fontWeight: FontWeight.bold),
  '34N': const TextStyle(fontSize: 34, color: Colors.black, fontWeight: FontWeight.normal),
  '34B': const TextStyle(fontSize: 34, color: Colors.black, fontWeight: FontWeight.bold),
};

Map<String, TextStyle> whiteTextStyles = {
  '14N': const TextStyle(fontSize: 14, color: Colors.white, fontWeight: FontWeight.normal),
  '14B': const TextStyle(fontSize: 14, color: Colors.white, fontWeight: FontWeight.bold),
  '16N': const TextStyle(fontSize: 16, color: Colors.white, fontWeight: FontWeight.normal),
  '16B': const TextStyle(fontSize: 16, color: Colors.white, fontWeight: FontWeight.bold),
  '18N': const TextStyle(fontSize: 18, color: Colors.white, fontWeight: FontWeight.normal),
  '18B': const TextStyle(fontSize: 18, color: Colors.white, fontWeight: FontWeight.bold),
  '20N': const TextStyle(fontSize: 20, color: Colors.white, fontWeight: FontWeight.normal),
  '20B': const TextStyle(fontSize: 20, color: Colors.white, fontWeight: FontWeight.bold),
  '22N': const TextStyle(fontSize: 22, color: Colors.white, fontWeight: FontWeight.normal),
  '22B': const TextStyle(fontSize: 22, color: Colors.white, fontWeight: FontWeight.bold),
  '24N': const TextStyle(fontSize: 24, color: Colors.white, fontWeight: FontWeight.normal),
  '24B': const TextStyle(fontSize: 24, color: Colors.white, fontWeight: FontWeight.bold),
  '26N': const TextStyle(fontSize: 26, color: Colors.white, fontWeight: FontWeight.normal),
  '26B': const TextStyle(fontSize: 26, color: Colors.white, fontWeight: FontWeight.bold),
  '28N': const TextStyle(fontSize: 28, color: Colors.white, fontWeight: FontWeight.normal),
  '28B': const TextStyle(fontSize: 28, color: Colors.white, fontWeight: FontWeight.bold),
  '30N': const TextStyle(fontSize: 30, color: Colors.white, fontWeight: FontWeight.normal),
  '30B': const TextStyle(fontSize: 30, color: Colors.white, fontWeight: FontWeight.bold),
  '32N': const TextStyle(fontSize: 32, color: Colors.white, fontWeight: FontWeight.normal),
  '32B': const TextStyle(fontSize: 32, color: Colors.white, fontWeight: FontWeight.bold),
  '34N': const TextStyle(fontSize: 34, color: Colors.white, fontWeight: FontWeight.normal),
  '34B': const TextStyle(fontSize: 34, color: Colors.white, fontWeight: FontWeight.bold),
  '36N': const TextStyle(fontSize: 36, color: Colors.white, fontWeight: FontWeight.normal),
  '36B': const TextStyle(fontSize: 36, color: Colors.white, fontWeight: FontWeight.bold),
  '38N': const TextStyle(fontSize: 38, color: Colors.white, fontWeight: FontWeight.normal),
  '38B': const TextStyle(fontSize: 38, color: Colors.white, fontWeight: FontWeight.bold),
  '40N': const TextStyle(fontSize: 40, color: Colors.white, fontWeight: FontWeight.normal),
  '40B': const TextStyle(fontSize: 40, color: Colors.white, fontWeight: FontWeight.bold),
};

Map<String, TextStyle> primaryTextStyles = {
  '14N': const TextStyle(fontSize: 14, color: Colors.lightGreen, fontWeight: FontWeight.normal),
  '14B': const TextStyle(fontSize: 14, color: Colors.lightGreen, fontWeight: FontWeight.bold),
  '16N': const TextStyle(fontSize: 16, color: Colors.lightGreen, fontWeight: FontWeight.normal),
  '16B': const TextStyle(fontSize: 16, color: Colors.lightGreen, fontWeight: FontWeight.bold),
  '18N': const TextStyle(fontSize: 18, color: Colors.lightGreen, fontWeight: FontWeight.normal),
  '18B': const TextStyle(fontSize: 18, color: Colors.lightGreen, fontWeight: FontWeight.bold),
  '20N': const TextStyle(fontSize: 20, color: Colors.lightGreen, fontWeight: FontWeight.normal),
  '20B': const TextStyle(fontSize: 20, color: Colors.lightGreen, fontWeight: FontWeight.bold),
  '22N': const TextStyle(fontSize: 22, color: Colors.lightGreen, fontWeight: FontWeight.normal),
  '22B': const TextStyle(fontSize: 22, color: Colors.lightGreen, fontWeight: FontWeight.bold),
  '24N': const TextStyle(fontSize: 24, color: Colors.lightGreen, fontWeight: FontWeight.normal),
  '24B': const TextStyle(fontSize: 24, color: Colors.lightGreen, fontWeight: FontWeight.bold),
  '26N': const TextStyle(fontSize: 26, color: Colors.lightGreen, fontWeight: FontWeight.normal),
  '26B': const TextStyle(fontSize: 26, color: Colors.lightGreen, fontWeight: FontWeight.bold),
  '28N': const TextStyle(fontSize: 28, color: Colors.lightGreen, fontWeight: FontWeight.normal),
  '28B': const TextStyle(fontSize: 28, color: Colors.lightGreen, fontWeight: FontWeight.bold),
  '30N': const TextStyle(fontSize: 30, color: Colors.lightGreen, fontWeight: FontWeight.normal),
  '30B': const TextStyle(fontSize: 30, color: Colors.lightGreen, fontWeight: FontWeight.bold),
  '32N': const TextStyle(fontSize: 32, color: Colors.lightGreen, fontWeight: FontWeight.normal),
  '32B': const TextStyle(fontSize: 32, color: Colors.lightGreen, fontWeight: FontWeight.bold),
  '34N': const TextStyle(fontSize: 34, color: Colors.lightGreen, fontWeight: FontWeight.normal),
  '34B': const TextStyle(fontSize: 34, color: Colors.lightGreen, fontWeight: FontWeight.bold),
};

TextStyle errorText = const TextStyle(color:  Colors.red , fontSize: 16);


