const SPLASH_SCREEN = "SPALSH_SCREEN";
const LOGIN_SCREEN = "LOGIN_SCREEN";
const MOBILE_VERIFICATION_SCREEN = 'MOBILE_VERIFICATION_SCREEN';
const FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD_SCREEN';
const REGISTER_USER_SCREEN = 'REGISTER_USER_SCREEN';
const DASHBOARD_SCREEN = 'DASHBOARD_SCREEN';
const PROFILE_SCREEN = 'PROFILE_SCREEN';
const ORDER_DETAILS_SCREEN = 'ORDDER_DETAILS_SCREEN';
const MENU_SCREEN = 'MENU_SCREEN';
const ADD_FOOD_SCREEN = 'ADD_FOOD_SCREEN';
const ADD_TABLE_SCREEN = 'ADD_TABLE_SCREEN';

const ARG_IS_DETAILS = 'ARG_IS_DETAILS';
const ARG_ORDER_ID = 'ARG_ORDER_ID';

